{% set version = "1.0.1" %}

package:
  name: virbot
  version: {{ version }}

source:
  url: https://github.com/rmcolq/RNA_virus_detector/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ed49c399fb725723986b2b2a46ae6494519d6db6ce696dd77068c3316645cc20

build:
  number: 0
  noarch: python
  script: python -m pip install .
  run_exports:
    - {{ pin_subpackage('virbot', max_pin="x") }}

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3
    - prodigal >=2.6.3 
    - hmmer >=3.3.2
    - diamond >=2.0.15
    - pandas >=1.5.2
    - git-lfs
    - conda
    - gitpython
    - git

test:
  commands:
    - virbot -h
    - virbot --input test/test_input.fa 

about:
  home: https://github.com/GreyGuoweiChen/RNA_virus_detector
  license: MIT
  license_file: LICENSE
  summary: VirBot RNA viral contig detector for metagenomic data
