{% set version = "1.0.6" %}

package:
  name: virbot
  version: {{ version }}

source:
  url: https://github.com/rmcolq/RNA_virus_detector/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5f8adb144cff54566d8d5a0d30e38a9a12a27c4c979d32416cc163671dca0fb0

build:
  number: 0
  noarch: python
  script: python -m pip install .
  run_exports:
    - {{ pin_subpackage('virbot', max_pin="x") }}

requirements:
  build:
    - python >=3.9
    - pip
    - conda
    - git
    - git-lfs
    - gitpython
    - libuuid
  run:
    - python >=3.9
    - prodigal >=2.6.3 
    - hmmer >=3.3.2
    - diamond >=2.0.15
    - pandas >=1.5.2
    - libuuid

test:
  commands:
    - virbot -h
    - virbot --input test/test_input.fa 

about:
  home: https://github.com/GreyGuoweiChen/RNA_virus_detector
  license: MIT
  license_file: LICENSE
  summary: VirBot RNA viral contig detector for metagenomic data
