{% set version = "1.0.9" %}

package:
  name: virbot
  version: {{ version }}

source:
  url: https://github.com/rmcolq/RNA_virus_detector/archive/refs/tags/v{{ version }}.tar.gz
  sha256: eb6a4eee44d5b8c5da156fb2bcac627e0cde5c25427abc21ec249ccb9f1e6ff2

build:
  number: 0
  noarch: python
  script: python -m pip install --no-build-isolation . --no-deps -vv 
  run_exports:
    - {{ pin_subpackage('virbot', max_pin="x") }}

requirements:
  build:
    - python >=3.9
    - pip
    - conda
    - git
    - git-lfs >=3.4.0
    - gitpython >=3.1.40
  run:
    - python >=3.9
    - pip
    - conda
    - git
    - git-lfs >=3.4.0
    - gitpython >=3.1.40
    - prodigal >=2.6.3 
    - hmmer >=3.4
    - diamond >=2.1.8
    - pandas >=2.1.4

test:
  commands:
    - virbot -h

about:
  home: https://github.com/GreyGuoweiChen/RNA_virus_detector
  license: MIT
  license_file: LICENSE
  summary: VirBot RNA viral contig detector for metagenomic data
