{% set version = "1.0.8" %}

package:
  name: virbot
  version: {{ version }}

source:
  url: https://github.com/rmcolq/RNA_virus_detector/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 20def65897009c9ef3f0caf9d80f515e732f98b2441c7b5f66a17bf464297f64

build:
  number: 0
  noarch: python
  script: python -m pip install --no-build-isolation . --no-deps -vv 
  run_exports:
    - {{ pin_subpackage('virbot', max_pin="x") }}

requirements:
  build:
    - python >=3.9
    - pip
    - conda
    - git
    - git-lfs >=3.4.0
    - gitpython >=3.1.40
  run:
    - python >=3.9
    - prodigal >=2.6.3 
    - hmmer >=3.4
    - diamond >=2.1.8
    - pandas >=2.1.4

test:
  requirements:
    - git-lfs
  commands:
    - virbot -h

about:
  home: https://github.com/GreyGuoweiChen/RNA_virus_detector
  license: MIT
  license_file: LICENSE
  summary: VirBot RNA viral contig detector for metagenomic data
